"""
AI Conversational Wizard endpoints.

Endpoints:
- GET /wizard-initial-question: Get the first wizard question
- POST /conversational-wizard: Generate next wizard question
- POST /wizard-finalize: Finalize wizard and generate project prompt
"""

from fastapi import APIRouter, HTTPException, Depends
from pydantic import BaseModel
from sqlalchemy.orm import Session
import google.generativeai as genai
import json

from app.core.config import settings
from app.core.logging import get_logger
from app.core.deps import get_current_user
from app.core.db import get_db
from app.models import User
from app.services.ai_usage import log_ai_usage, extract_usage_from_gemini_response

from .shared import GEMINI_MODEL, configure_gemini, clean_json_response

router = APIRouter()
logger = get_logger(__name__)


class WizardOption(BaseModel):
    label: str
    value: str
    description: str | None = None
    icon: str | None = None


# ==================== REQUEST/RESPONSE MODELS ====================

class ConversationTurn(BaseModel):
    step: int
    section_id: str | None = None
    question: str
    userChoice: str | None = None
    userFreeform: str | None = None
    userChoiceValue: str | None = None
    userChoiceDescription: str | None = None
    choiceType: str | None = None
    optionsSnapshot: list[WizardOption] | None = None
    draftPrompt: str | None = None
    displayText: str | None = None
    timestamp: str


class WizardQuestionRequest(BaseModel):
    conversation_history: list[ConversationTurn]


class WizardQuestionResponse(BaseModel):
    step: int
    section_id: str
    question: str
    options: list[WizardOption]
    allow_freeform: bool
    freeform_placeholder: str | None = None
    is_final_step: bool
    draft_prompt: str | None = None
    closing_remark: str | None = None
    is_model_ready: bool = False  # True quand le modèle est prêt à générer


class WizardFinalizeRequest(BaseModel):
    conversation_history: list[ConversationTurn]
    draft_prompt_override: str | None = None


class GraphPreview(BaseModel):
    description: str
    structure: str
    nodes_count: int
    example_nodes: list[str] | None = None
    parameters_count: int | None = None
    computed_count: int | None = None
    results_count: int | None = None


class WizardFinalizeResponse(BaseModel):
    user_intent: str
    graph_preview: GraphPreview
    suggested_scenarios: list[str]
    final_prompt: str


# ==================== ENDPOINTS ====================

@router.get("/wizard-initial-question", response_model=WizardQuestionResponse)
async def get_wizard_initial_question(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Returns the first question of the wizard, dynamically generated by AI 
    to provide fresh inspiration each time.
    Uses the user's smart_profile if available for personalized suggestions.
    """
    if not settings.GOOGLE_GENERATIVE_AI_API_KEY:
        # Fallback si pas de clé API
        return WizardQuestionResponse(
            step=1,
            section_id="target",
            question="Bonjour ! Quel modèle voulez-vous créer ?",
            options=[],
            allow_freeform=True,
            is_final_step=False
        )

    try:
        # Check if user has a smart profile for personalized suggestions
        smart_profile = current_user.smart_profile
        has_profile = smart_profile and smart_profile.get("completed", False)
        
        configure_gemini()
        model = genai.GenerativeModel(GEMINI_MODEL)
        
        if has_profile:
            # Use personalized prompt
            from app.services.wizard_prompts import WIZARD_WELCOME_PERSONALIZED_PROMPT
            
            # Map profession keys to French labels
            profession_labels = {
                "salarie": "salarié",
                "cadre": "cadre / manager",
                "freelance": "freelance / indépendant",
                "entrepreneur": "entrepreneur / chef d'entreprise",
                "liberal": "profession libérale",
                "investisseur": "investisseur",
                "retraite": "retraité",
                "etudiant": "étudiant",
                "reconversion": "en reconversion professionnelle",
            }

            # Map interest keys to French labels
            interest_labels = {
                "finance_perso": "finances personnelles",
                "business": "business / entrepreneuriat",
                "investissement": "investissement",
                "immobilier": "immobilier",
                "productivite": "productivité",
                "sante": "santé / bien-être",
                "ecologie": "écologie / impact environnemental",
                "side_project": "side-project / passion",
            }

            # Map level keys to French labels
            level_labels = {
                "debutant": "débutant (modèles simples)",
                "intermediaire": "intermédiaire",
                "avance": "avancé (modèles complexes)",
            }

            # Map tools keys to French labels
            tools_labels = {
                "excel": "Excel / Google Sheets",
                "notion": "Notion",
                "apps": "applications métier",
                "mental": "calcul mental / papier",
                "aucun": "aucun outil",
            }

            # Profession is now a list (multi-select)
            professions = smart_profile.get("profession", [])
            if isinstance(professions, str):
                professions = [professions]  # Backward compatibility
            profession_str = ", ".join([profession_labels.get(p, p) for p in professions]) or "non précisé"

            interests = smart_profile.get("interests", [])
            interests_str = ", ".join([interest_labels.get(i, i) for i in interests]) or "variés"

            level = smart_profile.get("level", "")
            level_label = level_labels.get(level, level) or "non précisé"

            tools = smart_profile.get("tools", [])
            tools_str = ", ".join([tools_labels.get(t, t) for t in tools]) or "non précisé"

            prompt = WIZARD_WELCOME_PERSONALIZED_PROMPT.format(
                profession=profession_str,
                interests=interests_str,
                level=level_label,
                tools=tools_str,
            )

            logger.info("Using personalized welcome prompt", profession=professions, interests=interests)
        else:
            # Use generic prompt
            from app.services.wizard_prompts import WIZARD_WELCOME_PROMPT
            prompt = WIZARD_WELCOME_PROMPT
            logger.info("Using generic welcome prompt (no profile)")
        
        # Appel IA pour générer les suggestions
        response = model.generate_content(
            prompt,
            generation_config=genai.types.GenerationConfig(
                temperature=0.6,
                response_mime_type="application/json"
            )
        )
        
        text = clean_json_response(response.text)
        logger.info("Welcome RAW response", text_preview=text[:200])

        try:
            raw_data = json.loads(text, strict=False)
            
            # Fonction de nettoyage récursif des clés (définition inline pour simplicité)
            def clean_json_keys(obj):
                if isinstance(obj, dict):
                    return {str(k).strip('"\' '): clean_json_keys(v) for k, v in obj.items()}
                if isinstance(obj, list):
                    return [clean_json_keys(x) for x in obj]
                return obj
            
            data = clean_json_keys(raw_data)
        except json.JSONDecodeError as e:
            logger.error("Welcome JSON Decode Error", raw_text=text, error=str(e))
            raise
        
        # Construction robuste des options
        raw_options = data.get("options", [])
        safe_options = []
        
        if not isinstance(raw_options, list):
            raw_options = []

        for i, opt in enumerate(raw_options):
            try:
                if not isinstance(opt, dict):
                    if isinstance(opt, str):
                        opt = {"label": opt, "value": opt}
                    else:
                        continue

                # Normalisation des clés (Label -> label, Value -> value)
                clean_opt = {k.lower(): v for k, v in opt.items()}
                
                # Valeurs par défaut obligatoires
                if "label" not in clean_opt:
                    clean_opt["label"] = str(clean_opt.get("value", f"Option {i+1}"))[:30]
                if "value" not in clean_opt:
                    clean_opt["value"] = clean_opt.get("label", "Value")
                
                # Filtrer pour ne garder que les champs valides du modèle
                valid_keys = {"label", "value", "description", "icon"}
                final_opt = {k: v for k, v in clean_opt.items() if k in valid_keys}
                
                safe_options.append(WizardOption(**final_opt))
            except Exception as e:
                logger.error(f"Skipping invalid welcome option {i}: {opt}", error=str(e))
                continue
        
        options = safe_options
        
        # Ajouter l'option "Autre chose" manuellement
        options.append(WizardOption(
            label="Autre chose...",
            value="custom_input", # Signal spécial pour le frontend
            description="Décrire ma propre idée",
            icon="Edit"
        ))
        
        return WizardQuestionResponse(
            step=1,
            section_id="target",
            question=data.get("question", "Bonjour ! Que voulez-vous créer aujourd'hui ?"),
            options=options,
            allow_freeform=True,
            freeform_placeholder="Décrivez votre idée...",
            is_final_step=False
        )

    except Exception as e:
        logger.error("Failed to generate welcome message", error=str(e))
        # Fallback en cas d'erreur
        return WizardQuestionResponse(
            step=1,
            section_id="target",
            question="Bonjour ! Que souhaitez-vous modéliser ?",
            options=[
                WizardOption(label="Finance / Rentabilité", value="Rentabilité projet", icon="DollarSign"),
                WizardOption(label="Autre chose...", value="custom_input", icon="Edit")
            ],
            allow_freeform=True,
            is_final_step=False
        )


@router.post("/conversational-wizard", response_model=WizardQuestionResponse)
async def generate_wizard_question(
    request: WizardQuestionRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Generate the next wizard question based on conversation history.
    The wizard guides the user step by step to build their personalized model.
    """
    import sys
    print("DEBUG: generate_wizard_question ALIVE v3", file=sys.stderr)

    try:
        if not settings.GOOGLE_GENERATIVE_AI_API_KEY:
            raise HTTPException(status_code=500, detail="AI API key not configured")

        from app.services.wizard_prompts import WIZARD_QUESTION_PROMPT

        # Step 1: Build conversation text
        logger.info("Step 1: Building conversation")
        conversation_text = ""
        if request.conversation_history:
            turns_text = []

            for turn in request.conversation_history:
                question_text = turn.question
                if turn.step == 1 or "architecte de modèles" in turn.question:
                    question_text = "Question d'accueil (Quel domaine modéliser ?)"

                lines = [
                    f"Étape {turn.step} (section: {turn.section_id or 'n/a'})",
                    f"Question posée: {question_text}",
                ]

                if turn.choiceType in ("option", "mixed") or turn.userChoiceValue:
                    if turn.userChoice:
                        lines.append(f"Choix (label): {turn.userChoice}")
                    if turn.userChoiceValue:
                        lines.append(f"Choix (valeur technique): {turn.userChoiceValue}")
                    if turn.userChoiceDescription:
                        lines.append(f"Choix (description): {turn.userChoiceDescription}")

                if turn.userFreeform:
                    label = "Précision libre" if turn.choiceType == "mixed" else "Réponse libre"
                    lines.append(f"{label}: {turn.userFreeform}")

                if turn.optionsSnapshot:
                    options_lines = []
                    for opt in turn.optionsSnapshot:
                        desc = f" | desc: {opt.description}" if opt.description else ""
                        options_lines.append(f"- {opt.label} | value: {opt.value}{desc}")
                    lines.append("Options proposées:\n" + "\n".join(options_lines))

                if turn.draftPrompt:
                    lines.append(f"Draft en cours: {turn.draftPrompt}")

                turns_text.append("\n".join(lines))

            conversation_text = "\n\n".join(turns_text)
        else:
            conversation_text = "(Première question - pas d'historique)"

        # Step 2: Anti-loop reinforcement
        logger.info("Step 2: Preparing prompt")
        if request.conversation_history:
            last_turn = request.conversation_history[-1]
            last_response = last_turn.userChoiceValue or last_turn.userFreeform or last_turn.userChoice
            if last_response:
                conversation_text += (
                    f"\n\n🚨 INSTRUCTION DE CONTEXTE IMMÉDIAT :\n"
                    f"L'utilisateur vient de répondre : '{last_response}'.\n"
                    f"TU DOIS IMPÉRATIVEMENT prendre en compte ce choix et avancer à l'étape suivante.\n"
                    f"INTERDICTION DE REPOSER la question précédente."
                )

        system_prompt = WIZARD_QUESTION_PROMPT.format(
            conversation_history=conversation_text
        )

        # Step 3: Call AI
        logger.info("Step 3: Calling Gemini")
        configure_gemini()
        model = genai.GenerativeModel(GEMINI_MODEL)

        response = model.generate_content(
            system_prompt,
            generation_config=genai.types.GenerationConfig(
                temperature=0.3,
                response_mime_type="application/json"
            )
        )
        
        # Step 4: Parse response
        logger.info("Step 4: Parsing response")
        text = clean_json_response(response.text)
        logger.info("Wizard RAW response", text_preview=text[:500])
        
        try:
            raw_data = json.loads(text, strict=False)
            logger.info("Wizard Parsed JSON keys (raw)", keys=list(raw_data.keys()))
            
            # Fonction de nettoyage récursif des clés
            def clean_json_keys(obj):
                if isinstance(obj, dict):
                    return {str(k).strip('"\' '): clean_json_keys(v) for k, v in obj.items()}
                if isinstance(obj, list):
                    return [clean_json_keys(x) for x in obj]
                return obj
            
            data = clean_json_keys(raw_data)
            import sys
            print(f"DEBUG: Cleaned Keys: {list(data.keys())}", file=sys.stderr)
            options_debug = data.get("options", [])
            if isinstance(options_debug, list) and len(options_debug) > 0:
                print(f"DEBUG: First Option Keys: {list(options_debug[0].keys())}", file=sys.stderr)

        except json.JSONDecodeError as e:
            logger.error("JSON Decode Error", raw_text=text, error=str(e))
            raise

        # Log AI usage
        prompt_tokens, completion_tokens = extract_usage_from_gemini_response(response)
        log_ai_usage(db, current_user.id, "wizard_question", GEMINI_MODEL, prompt_tokens, completion_tokens)

        is_final = bool(data.get("is_final_step", False))
        logger.info("Wizard question generated", step=len(request.conversation_history) + 1, is_final=is_final)

        # Construction robuste des options
        raw_options = data.get("options", [])
        safe_options = []
        
        if not isinstance(raw_options, list):
            logger.warning("Options is not a list", raw_type=type(raw_options))
            raw_options = []

        for i, opt in enumerate(raw_options):
            try:
                if not isinstance(opt, dict):
                    # Tentative de rattrapage si c'est une string
                    if isinstance(opt, str):
                        opt = {"label": opt, "value": opt}
                    else:
                        logger.warning(f"Option {i} is invalid type: {type(opt)}")
                        continue

                # Normalisation des clés (Label -> label, Value -> value) + STRIP quotes éventuelles dans les clés
                # Ex: '"label"' -> 'label'
                clean_opt = {str(k).strip('"\' ').lower(): v for k, v in opt.items()}
                
                # Valeurs par défaut obligatoires
                if "label" not in clean_opt:
                    clean_opt["label"] = str(clean_opt.get("value", f"Option {i+1}"))[:50]
                
                if "value" not in clean_opt:
                    clean_opt["value"] = clean_opt.get("label", "Value")
                
                # Filtrer pour ne garder que les champs valides du modèle
                valid_keys = {"label", "value", "description", "icon"}
                final_opt = {k: v for k, v in clean_opt.items() if k in valid_keys}
                
                # Validation Pydantic manuelle locale pour catcher l'erreur ici
                safe_options.append(WizardOption(**final_opt))

            except Exception as e:
                logger.error(f"Skipping invalid option {i}: {opt}", error=str(e))
                continue

        return WizardQuestionResponse(
            step=len(request.conversation_history) + 1,
            section_id=str(data.get("section_id", "domain")),
            question=str(data.get("question", "")),
            options=safe_options,
            allow_freeform=bool(data.get("allow_freeform", True)),
            freeform_placeholder=str(data.get("freeform_placeholder") or "") if data.get("freeform_placeholder") else None,
            is_final_step=is_final,
            draft_prompt=data.get("draft_prompt"),
            closing_remark=data.get("closing_remark"),
            is_model_ready=bool(data.get("model_ready", False))
        )

    except HTTPException:
        raise
    except Exception as e:
        logger.error("Global Wizard Error", error=str(e), exc_info=True)
        # Fallback de secours ultime pour ne pas planter le front
        return WizardQuestionResponse(
            step=len(request.conversation_history) + 1,
            section_id="error_fallback",
            question="Désolé, j'ai eu un petit souci technique. Pouvez-vous reformuler ?",
            options=[],
            allow_freeform=True,
            is_final_step=False
        )


@router.post("/wizard-finalize", response_model=WizardFinalizeResponse)
async def finalize_wizard(
    request: WizardFinalizeRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Generate the final summary and optimized prompt for graph creation.
    Analyzes the entire wizard conversation and builds an enriched prompt.
    """
    if not settings.GOOGLE_GENERATIVE_AI_API_KEY:
        raise HTTPException(status_code=500, detail="AI API key not configured")

    try:
        from app.services.wizard_prompts import WIZARD_FINALIZE_PROMPT

        turns_text = []
        for turn in request.conversation_history:
            lines = [
                f"Étape {turn.step} (section: {turn.section_id or 'n/a'})",
                f"Question: {turn.question}",
            ]

            if turn.choiceType in ("option", "mixed") or turn.userChoiceValue:
                if turn.userChoice:
                    lines.append(f"Choix (label): {turn.userChoice}")
                if turn.userChoiceValue:
                    lines.append(f"Choix (valeur technique): {turn.userChoiceValue}")
                if turn.userChoiceDescription:
                    lines.append(f"Choix (description): {turn.userChoiceDescription}")

            if turn.userFreeform:
                label = "Précision libre" if turn.choiceType == "mixed" else "Réponse libre"
                lines.append(f"{label}: {turn.userFreeform}")

            if turn.optionsSnapshot:
                options_lines = []
                for opt in turn.optionsSnapshot:
                    desc = f" | desc: {opt.description}" if opt.description else ""
                    options_lines.append(f"- {opt.label} | value: {opt.value}{desc}")
                lines.append("Options proposées:\n" + "\n".join(options_lines))

            if turn.draftPrompt:
                lines.append(f"Draft en cours: {turn.draftPrompt}")

            turns_text.append("\n".join(lines))

        conversation_text = "\n\n".join(turns_text) if turns_text else "(Pas d'historique)"

        system_prompt = WIZARD_FINALIZE_PROMPT.format(
            conversation_history=conversation_text,
            draft_prompt_override=request.draft_prompt_override or ""
        )

        configure_gemini()
        model = genai.GenerativeModel(GEMINI_MODEL)

        response = model.generate_content(
            system_prompt,
            generation_config=genai.types.GenerationConfig(
                temperature=0.2,
                response_mime_type="application/json"
            )
        )

        text = clean_json_response(response.text)
        data = json.loads(text, strict=False)

        # Log AI usage
        prompt_tokens, completion_tokens = extract_usage_from_gemini_response(response)
        log_ai_usage(db, current_user.id, "wizard_finalize", GEMINI_MODEL, prompt_tokens, completion_tokens)

        logger.info("Wizard finalized", nodes_count=data.get("graph_preview", {}).get("nodes_count", 0))

        return WizardFinalizeResponse(
            user_intent=data.get("user_intent", ""),
            graph_preview=GraphPreview(**data.get("graph_preview", {})),
            suggested_scenarios=data.get("suggested_scenarios", []),
            final_prompt=data.get("final_prompt", "")
        )

    except json.JSONDecodeError as e:
        logger.error("Failed to parse wizard finalize JSON", error=str(e))
        raise HTTPException(status_code=500, detail=f"AI returned invalid JSON: {str(e)}")
    except Exception as e:
        logger.error("Wizard finalization failed", error=str(e), exc_info=True)
        raise HTTPException(status_code=500, detail=f"Wizard finalization failed: {str(e)}")
