"""Add project collaborators

Revision ID: 4c81d9590bc6
Revises: 006_add_node_composite_id
Create Date: 2025-11-30 21:12:38.874098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c81d9590bc6'
down_revision: Union[str, None] = '006_add_node_composite_id'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_collaborator',
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    op.create_foreign_key(None, 'composite', 'user', ['user_id'], ['id'])
    op.alter_column('node', 'provider_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('uq_node_project_slug', table_name='node')
    op.create_unique_constraint('uq_node_project_slug', 'node', ['project_id', 'slug'])
    op.create_foreign_key(None, 'node', 'composite', ['composite_id'], ['id'], ondelete='SET NULL')
    op.drop_index('uq_project_public_view_token', table_name='project')
    op.create_unique_constraint(None, 'project', ['public_view_token'])
    op.create_foreign_key(None, 'project', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_constraint(None, 'project', type_='unique')
    op.create_index('uq_project_public_view_token', 'project', ['public_view_token'], unique=True)
    op.drop_constraint(None, 'node', type_='foreignkey')
    op.drop_constraint('uq_node_project_slug', 'node', type_='unique')
    op.create_index('uq_node_project_slug', 'node', ['project_id', 'slug'], unique=True)
    op.alter_column('node', 'provider_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'composite', type_='foreignkey')
    op.drop_table('project_collaborator')
    # ### end Alembic commands ###
